---
# defaults file for roles/consul
consul_version: "1.15.4"

consul_user: consul
consul_group: consul

consul_data_dir: /opt/consul
consul_config_dir: /etc/consul.d

consul_bind_addr: "127.0.0.1"
consul_client_addr: "0.0.0.0"
consul_datacenter: "dc1"
